# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginEng.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as sql
import playUsers


class loginForm(object):
    def __init__(self, numberOfPlayer):
        self.numberOfPlayer = numberOfPlayer
        self.playerNickname = ''

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(404, 574)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.gradientBackground = QtWidgets.QLabel(Form)
        self.gradientBackground.setGeometry(QtCore.QRect(50, 90, 291, 361))
        font = QtGui.QFont()
        font.setBold(False)
        self.gradientBackground.setFont(font)
        self.gradientBackground.setStyleSheet("background-color: rgb(16, 31, 25);\n"
"border-color: 3 px rgb(255, 170, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0.0170455, stop:0 rgba(24, 47, 38, 255), stop:0.0454545 rgba(24, 47, 38, 255), stop:0.0795455 rgba(30, 58, 47, 255), stop:0.369318 rgba(255, 170, 0, 255), stop:0.465909 rgba(255, 170, 0, 255), stop:0.517045 rgba(255, 170, 0, 255), stop:0.528409 rgba(255, 170, 0, 255), stop:0.670455 rgba(255, 170, 0, 255), stop:0.935 rgba(24, 47, 38, 255));\n"
"")
        self.gradientBackground.setText("")
        self.gradientBackground.setObjectName("gradientBackground")
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(90, 120, 211, 301))
        self.background.setStyleSheet("background-color: rgb(24, 47, 38);\n"
"background-color: rgb(24, 47, 38);\n"
"border-radius:10px;\n"
"")
        self.background.setText("")
        self.background.setObjectName("background")
        self.loginText = QtWidgets.QLabel(Form)
        self.loginText.setGeometry(QtCore.QRect(136, 130, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        self.loginText.setFont(font)
        self.loginText.setStyleSheet("color: rgb(255, 170, 0);")
        self.loginText.setObjectName("loginText")
        self.usernameLine = QtWidgets.QLineEdit(Form)
        self.usernameLine.setGeometry(QtCore.QRect(127, 210, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.usernameLine.setFont(font)
        self.usernameLine.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgb(255, 170, 0);\n"
"color: rgb(80, 93, 94);\n"
"padding-bottom: 7px;")
        self.usernameLine.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameLine.setObjectName("usernameLine")
        self.passwordLine = QtWidgets.QLineEdit(Form)
        self.passwordLine.setGeometry(QtCore.QRect(127, 270, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.passwordLine.setFont(font)
        self.passwordLine.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgb(255, 170, 0);\n"
"color: rgb(80, 93, 94);\n"
"padding-bottom: 7px;")
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLine.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordLine.setDragEnabled(False)
        self.passwordLine.setObjectName("passwordLine")
        self.loginButton = QtWidgets.QPushButton(Form)
        self.loginButton.setGeometry(QtCore.QRect(130, 340, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton#loginButton{\n"
"    background-color: rgb(255, 170, 0);\n"
"    color: rgb(255, 104, 3);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#loginButton:pressed{\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"    background-color: rgb(255, 206, 12);\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"\n"
"QPushButton#loginButton:hover{\n"
"    background-color: rgb(255, 206, 12);\n"
"}\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.statusLabel = QtWidgets.QLabel(Form)
        self.statusLabel.setGeometry(QtCore.QRect(95, 170, 201, 51))
        font = QtGui.QFont()
        font.setBold(False)
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("color: rgb(255, 46, 56);")
        self.statusLabel.setText("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.changePassword = QtWidgets.QLabel(Form)
        self.changePassword.setGeometry(QtCore.QRect(144, 390, 101, 31))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.changePassword.setFont(font)
        self.changePassword.setStyleSheet("color: rgb(59, 115, 92);\n"
"color: rgb(48, 94, 66);")
        self.changePassword.setAlignment(QtCore.Qt.AlignCenter)
        self.changePassword.setObjectName("changePassword")
        self.closeLabel = QtWidgets.QLabel(Form)
        self.closeLabel.setGeometry(QtCore.QRect(324, 90, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.closeLabel.setFont(font)
        self.closeLabel.setStyleSheet("color: rgb(255, 170, 0);")
        self.closeLabel.setObjectName("closeLabel")
        self.closeButton = QtWidgets.QPushButton(Form)
        self.closeButton.setGeometry(QtCore.QRect(322, 95, 14, 17))
        self.closeButton.setStyleSheet("QPushButton { background-color: transparent; border: 0px };")
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        if (1 in self.numberOfPlayer) == True:
            self.update_db(1)
        if (2 in self.numberOfPlayer) == True:
            self.update_db(2)
        if (3 in self.numberOfPlayer) == True:
            self.update_db(3)
        if (4 in self.numberOfPlayer) == True:
            self.update_db(4)

        # Obsługa przycisków
        self.loginButton.clicked.connect(self.login)
        self.closeButton.clicked.connect(Form.close)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.loginText.setText(_translate("Form", "LOG IN"))
        self.usernameLine.setPlaceholderText(_translate("Form", "USERNAME"))
        self.passwordLine.setPlaceholderText(_translate("Form", "PASSWORD"))
        self.loginButton.setText(_translate("Form", "LOG IN"))
        self.changePassword.setText(_translate("Form", "Change password"))
        self.closeLabel.setText(_translate("Form", "x"))

    def login(self):
        try:
            db = sql.connect('siema.db')  # łączymy się do bazy
            c = db.cursor()  # dodajemy kursor

            # c.execute("""CREATE TABLE logged_users (
            #                 id integer,
            #                 username text UNIQUE,
            #                 coins integer
            #                 )""")

            username = self.usernameLine.text()
            password = self.passwordLine.text()

            query = "SELECT username, password, coins from users where username like '" + username + "'and password like '" + password + "'"
            c.execute(query)
            db.commit()

            result = c.fetchone()


            if username == "" or password == "":
                self.statusLabel.setText("Please fill in all the required fields")
            elif result == None:
                self.statusLabel.setText("Incorrect username or password")
            else:
                self.playerNickname = username
                # playUsers.usersForm.loginInfo(self.loginStatus, self.playerNickname)
                self.statusLabel.setStyleSheet("color: rgb(51, 204, 51);")
                self.statusLabel.setText("You are logged in")
                self.loginButton.setEnabled(False)

                try:
                    coins = result[2]
                    c.execute(
                        "INSERT INTO logged_users (id,username,coins) VALUES (?,?,?)", (0, username, coins))
                    db.commit()
                    self.update_db(self.numberOfPlayer[-1])

                except sql.Error as e:
                    self.statusLabel.setStyleSheet("color: rgb(255, 46, 56);")
                    self.statusLabel.setText("This user is already logged in")


        except sql.Error as e:
            self.statusLabel.setStyleSheet("color: rgb(255, 46, 56);")
            self.statusLabel.setText("Error")

    def update_db(self, user_id):
        try:
            db = sql.connect('siema.db')  # łączymy się do bazy
            c = db.cursor()  # dodajemy kursor

            c.execute(
                "UPDATE logged_users SET id = {} WHERE id = 0".format(user_id))
            # "INSERT INTO logged_users (id,username,password) VALUES (?,?,?)", (0, self.username, self.password))
            db.commit()

        except sql.Error as e:
            print("Error")