# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playerChange.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time


class changeForm(object):
    def __init__(self, board):
        self.board = board
        self.language = board.language
        self.board_timer = board.timer
        self.frontendLogic = board.frontend_logic

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1850, 940)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.backgroundLabel = QtWidgets.QLabel(Form)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 1850, 940))
        self.backgroundLabel.setText("")
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.nicknameLabel = QtWidgets.QLabel(Form)
        self.nicknameLabel.setGeometry(QtCore.QRect(368, 457, 1091, 141))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.nicknameLabel.setFont(font)
        self.nicknameLabel.setStyleSheet("color: rgb(255, 156, 17);")
        self.nicknameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nicknameLabel.setObjectName("nicknameLabel")
        self.playButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.playButton.setFont(font)
        self.playButton.setStyleSheet("QPushButton#playButton{\n"
"    background-color: rgb(255, 170, 0);\n"
"    color: rgb(255, 104, 3);\n"
"    border-radius: 45px;\n"
"}\n"
"\n"
"QPushButton#pplayButton:pressed{\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"    background-color: rgb(255, 206, 12);\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"\n"
"QPushButton#playButton:hover{\n"
"    background-color: rgb(255, 206, 12);\n"
"}\n"
"")
        self.playButton.setObjectName("playButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        if self.frontendLogic.current_player.type != "player":
            self.playButton.setVisible(False)

        else:
            self.playButton.setVisible(True)
            self.playButton.clicked.connect(self.board.enable_buttons)

        self.playButton.clicked.connect(Form.close)
        self.playButton.clicked.connect(self.board.reset_timer)
        self.playButton.clicked.connect(self.board_timer.start)

        # Obsługa języków
        if self.language == 1:
            self.backgroundLabel.setStyleSheet("image: url(:/images/playersChange.png);")
            self.playButton.setGeometry(QtCore.QRect(870, 720, 91, 91))
        if self.language == 2:
            self.backgroundLabel.setStyleSheet("image: url(:/images/playersChangePL.png);")
            self.playButton.setGeometry(QtCore.QRect(870, 660, 91, 91))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Change user"))
        self.nicknameLabel.setText(_translate("Form", self.frontendLogic.current_player.name))
        if self.language == 1:
            self.playButton.setText(_translate("Form", "PLAY"))
        if self.language == 2:
            self.playButton.setText(_translate("Form", "GRAJ"))
