# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playUsers.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import playOptions, loginEng, registerEng
import sqlite3 as sql


class usersForm(object):
    def __init__(self, playersNumber, computersNumber, betting):
        self.playersNumber = playersNumber
        self.computersNumber = computersNumber
        self.betting = betting
        self.gameLevel = 0
        self.computerOneLevel = 0
        self.computerTwoLevel = 0
        self.computerThreeLevel = 0
        self.computerFourLevel = 0
        self.numberOfPlayer = 0

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(530, 732)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 511, 711))
        self.background.setStyleSheet("background-color: rgb(24, 47, 38);")
        self.background.setText("")
        self.background.setObjectName("background")
        self.returnIcon = QtWidgets.QLabel(Form)
        self.returnIcon.setGeometry(QtCore.QRect(471, 8, 31, 31))
        self.returnIcon.setStyleSheet("border-image: url(:/images/return.png);")
        self.returnIcon.setText("")
        self.returnIcon.setObjectName("returnIcon")
        self.returnButton = QtWidgets.QPushButton(Form)
        self.returnButton.setGeometry(QtCore.QRect(470, 10, 31, 31))
        self.returnButton.setStyleSheet("QPushButton { background-color: transparent; border: 0px };")
        self.returnButton.setText("")
        self.returnButton.setObjectName("returnButton")
        self.backgroundDark = QtWidgets.QLabel(Form)
        self.backgroundDark.setGeometry(QtCore.QRect(40, 20, 431, 671))
        self.backgroundDark.setStyleSheet("background-color:rgba(0, 0, 0, 100);\n"
                                          "border-radius:10px;\n"
                                          "")
        self.backgroundDark.setText("")
        self.backgroundDark.setObjectName("backgroundDark")
        self.difficultyLabel = QtWidgets.QLabel(Form)
        self.difficultyLabel.setGeometry(QtCore.QRect(160, 40, 191, 41))
        self.difficultyLabel.setStyleSheet("image: url(:/images/difficulty.png);")
        self.difficultyLabel.setText("")
        self.difficultyLabel.setObjectName("difficultyLabel")
        self.playerOneLabel = QtWidgets.QLabel(Form)
        self.playerOneLabel.setGeometry(QtCore.QRect(100, 181, 151, 31))
        self.playerOneLabel.setStyleSheet("image: url(:/images/playerOne.png);")
        self.playerOneLabel.setText("")
        self.playerOneLabel.setObjectName("playerOneLabel")
        self.playerTwoLabel = QtWidgets.QLabel(Form)
        self.playerTwoLabel.setGeometry(QtCore.QRect(290, 181, 121, 31))
        self.playerTwoLabel.setStyleSheet("image: url(:/images/playerTwo.png);")
        self.playerTwoLabel.setText("")
        self.playerTwoLabel.setObjectName("playerTwoLabel")
        self.playerThreeLabel = QtWidgets.QLabel(Form)
        self.playerThreeLabel.setGeometry(QtCore.QRect(110, 301, 121, 31))
        self.playerThreeLabel.setStyleSheet("image: url(:/images/playerThree.png);")
        self.playerThreeLabel.setText("")
        self.playerThreeLabel.setObjectName("playerThreeLabel")
        self.playerFourLabel = QtWidgets.QLabel(Form)
        self.playerFourLabel.setGeometry(QtCore.QRect(260, 301, 181, 31))
        self.playerFourLabel.setStyleSheet("image: url(:/images/playerFour.png);")
        self.playerFourLabel.setText("")
        self.playerFourLabel.setObjectName("playerFourLabel")
        self.compOneLabel = QtWidgets.QLabel(Form)
        self.compOneLabel.setGeometry(QtCore.QRect(72, 451, 161, 31))
        self.compOneLabel.setStyleSheet("image: url(:/images/computerOne.png);")
        self.compOneLabel.setText("")
        self.compOneLabel.setObjectName("compOneLabel")
        self.logoCards = QtWidgets.QLabel(Form)
        self.logoCards.setGeometry(QtCore.QRect(60, 10, 61, 51))
        self.logoCards.setStyleSheet("image: url(:/images/logoCards.png);")
        self.logoCards.setText("")
        self.logoCards.setObjectName("logoCards")
        self.easyGameButton = QtWidgets.QPushButton(Form)
        self.easyGameButton.setGeometry(QtCore.QRect(70, 81, 91, 51))
        self.easyGameButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                          "border: 0px;")
        self.easyGameButton.setText("")
        self.easyGameButton.setObjectName("easyGameButton")
        self.mediumGameButton = QtWidgets.QPushButton(Form)
        self.mediumGameButton.setGeometry(QtCore.QRect(193, 84, 121, 45))
        self.mediumGameButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                            "border: 0px;")
        self.mediumGameButton.setText("")
        self.mediumGameButton.setObjectName("mediumGameButton")
        self.hardGameButton = QtWidgets.QPushButton(Form)
        self.hardGameButton.setGeometry(QtCore.QRect(343, 81, 91, 51))
        self.hardGameButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                          "border: 0px;")
        self.hardGameButton.setText("")
        self.hardGameButton.setObjectName("hardGameButton")
        self.compTwoLabel = QtWidgets.QLabel(Form)
        self.compTwoLabel.setGeometry(QtCore.QRect(290, 451, 151, 31))
        self.compTwoLabel.setStyleSheet("image: url(:/images/computerTwo.png);")
        self.compTwoLabel.setText("")
        self.compTwoLabel.setObjectName("compTwoLabel")
        self.compThreeLabel = QtWidgets.QLabel(Form)
        self.compThreeLabel.setGeometry(QtCore.QRect(72, 541, 151, 31))
        self.compThreeLabel.setStyleSheet("image: url(:/images/computerThree.png);")
        self.compThreeLabel.setText("")
        self.compThreeLabel.setObjectName("compThreeLabel")
        self.compFourLabel = QtWidgets.QLabel(Form)
        self.compFourLabel.setGeometry(QtCore.QRect(290, 541, 151, 31))
        self.compFourLabel.setStyleSheet("image: url(:/images/computerFour.png);")
        self.compFourLabel.setText("")
        self.compFourLabel.setObjectName("compFourLabel")
        self.easyLabel = QtWidgets.QLabel(Form)
        self.easyLabel.setGeometry(QtCore.QRect(86, 121, 61, 61))
        self.easyLabel.setStyleSheet("image: url(:/images/easyTiming.png);")
        self.easyLabel.setText("")
        self.easyLabel.setObjectName("easyLabel")
        self.mediumLabel = QtWidgets.QLabel(Form)
        self.mediumLabel.setGeometry(QtCore.QRect(223, 121, 61, 61))
        self.mediumLabel.setStyleSheet("image: url(:/images/mediumTiming.png);")
        self.mediumLabel.setText("")
        self.mediumLabel.setObjectName("mediumLabel")
        self.hardLabel = QtWidgets.QLabel(Form)
        self.hardLabel.setGeometry(QtCore.QRect(358, 121, 61, 61))
        self.hardLabel.setStyleSheet("image: url(:/images/hardTiming.png);")
        self.hardLabel.setText("")
        self.hardLabel.setObjectName("hardLabel")
        self.compOneEasyButton = QtWidgets.QPushButton(Form)
        self.compOneEasyButton.setGeometry(QtCore.QRect(65, 481, 51, 31))
        self.compOneEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                             "border: 0px;")
        self.compOneEasyButton.setText("")
        self.compOneEasyButton.setObjectName("compOneEasyButton")
        self.compOneMediumButton = QtWidgets.QPushButton(Form)
        self.compOneMediumButton.setGeometry(QtCore.QRect(123, 481, 61, 31))
        self.compOneMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                               "border: 0px;")
        self.compOneMediumButton.setText("")
        self.compOneMediumButton.setObjectName("compOneMediumButton")
        self.compOneHardButton = QtWidgets.QPushButton(Form)
        self.compOneHardButton.setGeometry(QtCore.QRect(190, 481, 51, 31))
        self.compOneHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                             "border: 0px;")
        self.compOneHardButton.setText("")
        self.compOneHardButton.setObjectName("compOneHardButton")

        self.playerOneNickname = QtWidgets.QLabel(Form)
        self.playerOneNickname.setGeometry(QtCore.QRect(96, 220, 151, 31))
        self.playerOneNickname.setText("")
        self.playerOneNickname.setAlignment(QtCore.Qt.AlignCenter)
        self.playerOneNickname.setObjectName("playerOneNickname")
        self.playerTwoNickname = QtWidgets.QLabel(Form)
        self.playerTwoNickname.setGeometry(QtCore.QRect(274, 220, 151, 31))
        self.playerTwoNickname.setText("")
        self.playerTwoNickname.setAlignment(QtCore.Qt.AlignCenter)
        self.playerTwoNickname.setObjectName("playerTwoNickname")
        self.playerThreeNickname = QtWidgets.QLabel(Form)
        self.playerThreeNickname.setGeometry(QtCore.QRect(96, 341, 151, 31))
        self.playerThreeNickname.setText("")
        self.playerThreeNickname.setAlignment(QtCore.Qt.AlignCenter)
        self.playerThreeNickname.setObjectName("playerThreeNickname")
        self.playerFourNickname = QtWidgets.QLabel(Form)
        self.playerFourNickname.setGeometry(QtCore.QRect(274, 341, 151, 31))
        self.playerFourNickname.setStyleSheet("color: rgb(255, 85, 0);")
        self.playerFourNickname.setText("")
        self.playerFourNickname.setAlignment(QtCore.Qt.AlignCenter)
        self.playerFourNickname.setObjectName("playerFourNickname")

        self.playerOneLogin = QtWidgets.QPushButton(Form)
        self.playerOneLogin.setGeometry(QtCore.QRect(110, 221, 121, 31))
        self.playerOneLogin.setStyleSheet("image: url(:/images/logIn.png);\n"
                                          "border: 0px;")
        self.playerOneLogin.setText("")
        self.playerOneLogin.setObjectName("playerOneLogin")
        self.playerOneRegister = QtWidgets.QPushButton(Form)
        self.playerOneRegister.setGeometry(QtCore.QRect(120, 261, 101, 31))
        self.playerOneRegister.setStyleSheet("image: url(:/images/registerButton.png);\n"
                                             "border: 0px;")
        self.playerOneRegister.setText("")
        self.playerOneRegister.setObjectName("playerOneRegister")

        self.playerTwoLogin = QtWidgets.QPushButton(Form)
        self.playerTwoLogin.setGeometry(QtCore.QRect(290, 221, 121, 31))
        self.playerTwoLogin.setStyleSheet("image: url(:/images/logIn.png);\n"
                                          "border: 0px;")
        self.playerTwoLogin.setText("")
        self.playerTwoLogin.setObjectName("playerTwoLogin")
        self.playerTwoRegister = QtWidgets.QPushButton(Form)
        self.playerTwoRegister.setGeometry(QtCore.QRect(300, 261, 101, 31))
        self.playerTwoRegister.setStyleSheet("image: url(:/images/registerButton.png);\n"
                                             "border: 0px;")
        self.playerTwoRegister.setText("")
        self.playerTwoRegister.setObjectName("playerTwoRegister")
        self.playerThreeRegister = QtWidgets.QPushButton(Form)
        self.playerThreeRegister.setGeometry(QtCore.QRect(120, 381, 101, 31))
        self.playerThreeRegister.setStyleSheet("image: url(:/images/registerButton.png);\n"
                                               "border: 0px;")
        self.playerThreeRegister.setText("")
        self.playerThreeRegister.setObjectName("playerThreeRegister")
        self.playerThreeLogin = QtWidgets.QPushButton(Form)
        self.playerThreeLogin.setGeometry(QtCore.QRect(110, 341, 121, 31))
        self.playerThreeLogin.setStyleSheet("image: url(:/images/logIn.png);\n"
                                            "border: 0px;")
        self.playerThreeLogin.setText("")
        self.playerThreeLogin.setObjectName("playerThreeLogin")
        self.playerFourRegister = QtWidgets.QPushButton(Form)
        self.playerFourRegister.setGeometry(QtCore.QRect(300, 381, 101, 31))
        self.playerFourRegister.setStyleSheet("image: url(:/images/registerButton.png);\n"
                                              "border: 0px;")
        self.playerFourRegister.setText("")
        self.playerFourRegister.setObjectName("playerFourRegister")
        self.playerFourLogin = QtWidgets.QPushButton(Form)
        self.playerFourLogin.setGeometry(QtCore.QRect(290, 341, 121, 31))
        self.playerFourLogin.setStyleSheet("image: url(:/images/logIn.png);\n"
                                           "border: 0px;")
        self.playerFourLogin.setText("")
        self.playerFourLogin.setObjectName("playerFourLogin")

        self.compTwoMediumButton = QtWidgets.QPushButton(Form)
        self.compTwoMediumButton.setGeometry(QtCore.QRect(333, 481, 61, 31))
        self.compTwoMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                               "border: 0px;")
        self.compTwoMediumButton.setText("")
        self.compTwoMediumButton.setObjectName("compTwoMediumButton")
        self.compTwoHardButton = QtWidgets.QPushButton(Form)
        self.compTwoHardButton.setGeometry(QtCore.QRect(400, 481, 51, 31))
        self.compTwoHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                             "border: 0px;")
        self.compTwoHardButton.setText("")
        self.compTwoHardButton.setObjectName("compTwoHardButton")
        self.compTwoEasyButton = QtWidgets.QPushButton(Form)
        self.compTwoEasyButton.setGeometry(QtCore.QRect(275, 481, 51, 31))
        self.compTwoEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                             "border: 0px;")
        self.compTwoEasyButton.setText("")
        self.compTwoEasyButton.setObjectName("compTwoEasyButton")
        self.compThreeMediumButton = QtWidgets.QPushButton(Form)
        self.compThreeMediumButton.setGeometry(QtCore.QRect(118, 571, 61, 31))
        self.compThreeMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                                 "border: 0px;")
        self.compThreeMediumButton.setText("")
        self.compThreeMediumButton.setObjectName("compThreeMediumButton")
        self.compThreeHardButton = QtWidgets.QPushButton(Form)
        self.compThreeHardButton.setGeometry(QtCore.QRect(185, 571, 51, 31))
        self.compThreeHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                               "border: 0px;")
        self.compThreeHardButton.setText("")
        self.compThreeHardButton.setObjectName("compThreeHardButton")
        self.compThreeEasyButton = QtWidgets.QPushButton(Form)
        self.compThreeEasyButton.setGeometry(QtCore.QRect(60, 571, 51, 31))
        self.compThreeEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                               "border: 0px;")
        self.compThreeEasyButton.setText("")
        self.compThreeEasyButton.setObjectName("compThreeEasyButton")
        self.compFourHardButton = QtWidgets.QPushButton(Form)
        self.compFourHardButton.setGeometry(QtCore.QRect(397, 571, 51, 31))
        self.compFourHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                              "border: 0px;")
        self.compFourHardButton.setText("")
        self.compFourHardButton.setObjectName("compFourHardButton")
        self.compFourEasyButton = QtWidgets.QPushButton(Form)
        self.compFourEasyButton.setGeometry(QtCore.QRect(272, 571, 51, 31))
        self.compFourEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                              "border: 0px;")
        self.compFourEasyButton.setText("")
        self.compFourEasyButton.setObjectName("compFourEasyButton")
        self.compFourMediumButton = QtWidgets.QPushButton(Form)
        self.compFourMediumButton.setGeometry(QtCore.QRect(330, 571, 61, 31))
        self.compFourMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                                "border: 0px;")
        self.compFourMediumButton.setText("")
        self.compFourMediumButton.setObjectName("compFourMediumButton")
        self.nextIcon = QtWidgets.QLabel(Form)
        self.nextIcon.setGeometry(QtCore.QRect(128, 590, 251, 111))
        self.nextIcon.setStyleSheet("image: url(:/images/next.png);")
        self.nextIcon.setText("")
        self.nextIcon.setObjectName("nextIcon")
        self.nextButton = QtWidgets.QPushButton(Form)
        self.nextButton.setGeometry(QtCore.QRect(212, 620, 81, 51))
        self.nextButton.setStyleSheet("QPushButton { background-color: transparent; border: 0px };")
        self.nextButton.setText("")
        self.nextButton.setObjectName("nextButton")

        self.background.raise_()
        self.backgroundDark.raise_()
        self.difficultyLabel.raise_()
        self.playerOneLabel.raise_()
        self.playerTwoLabel.raise_()
        self.playerThreeLabel.raise_()
        self.playerFourLabel.raise_()
        self.compOneLabel.raise_()
        self.logoCards.raise_()
        self.returnIcon.raise_()
        self.easyGameButton.raise_()
        self.mediumGameButton.raise_()
        self.hardGameButton.raise_()
        self.playerOneNickname.raise_()
        self.playerTwoNickname.raise_()
        self.playerThreeNickname.raise_()
        self.playerFourNickname.raise_()
        self.playerOneLogin.raise_()
        self.playerOneRegister.raise_()
        self.compTwoLabel.raise_()
        self.compThreeLabel.raise_()
        self.compFourLabel.raise_()
        self.easyLabel.raise_()
        self.mediumLabel.raise_()
        self.hardLabel.raise_()
        self.compOneEasyButton.raise_()
        self.compOneMediumButton.raise_()
        self.compOneHardButton.raise_()
        self.playerTwoLogin.raise_()
        self.playerTwoRegister.raise_()
        self.playerThreeRegister.raise_()
        self.playerThreeLogin.raise_()
        self.playerFourRegister.raise_()
        self.playerFourLogin.raise_()
        self.compTwoMediumButton.raise_()
        self.compTwoHardButton.raise_()
        self.compTwoEasyButton.raise_()
        self.compThreeMediumButton.raise_()
        self.compThreeHardButton.raise_()
        self.compThreeEasyButton.raise_()
        self.compFourHardButton.raise_()
        self.compFourEasyButton.raise_()
        self.compFourMediumButton.raise_()
        self.nextIcon.raise_()
        self.nextButton.raise_()
        self.returnButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        if self.playersNumber == 0:
            self.zeroPlayers()
        if self.playersNumber == 1:
            self.onePlayer()
        if self.playersNumber == 2:
            self.twoPlayers()
        if self.playersNumber == 3:
            self.threePlayers()
        if self.playersNumber == 4:
            self.fourPlayers()
        if self.computersNumber == 0:
            self.zeroComputers()
        if self.computersNumber == 1:
            self.oneComputer()
        if self.computersNumber == 2:
            self.twoComputers()
        if self.computersNumber == 3:
            self.threeComputers()
        if self.computersNumber == 4:
            self.fourComputers()

        # Obsługa przycisków
        self.returnButton.clicked.connect(self.returnToOptions)
        self.returnButton.clicked.connect(Form.close)

        self.easyGameButton.clicked.connect(self.easyLevel)
        self.mediumGameButton.clicked.connect(self.mediumLevel)
        self.hardGameButton.clicked.connect(self.hardLevel)

        # self.playerOneLogin.clicked.connect(self.show_login)
        # self.playerTwoLogin.clicked.connect(self.show_login)
        # self.playerThreeLogin.clicked.connect(self.show_login)
        # self.playerFourLogin.clicked.connect(self.show_login)

        # self.playerOneRegister.clicked.connect(self.show_register)
        # self.playerTwoRegister.clicked.connect(self.show_register)
        # self.playerThreeRegister.clicked.connect(self.show_register)
        # self.playerFourRegister.clicked.connect(self.show_register)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

    def returnToOptions(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = playOptions.playOptionsForm()
        self.ui.setupUi(self.window)
        self.window.show()

    def zeroPlayers(self):
        self.playerOneLabel.setStyleSheet("image: url(:/images/playerOneInactive.png);")
        self.playerTwoLabel.setStyleSheet("image: url(:/images/playerTwoInactive.png);")
        self.playerThreeLabel.setStyleSheet("image: url(:/images/playerThreeInactive.png);")
        self.playerFourLabel.setStyleSheet("image: url(:/images/playerFourInactive.png);")

        self.playerOneLogin.setStyleSheet("image: url(:/images/logInInactive.png);\n"
                                          "border: 0px;")
        self.playerOneRegister.setStyleSheet("image: url(:/images/registerButtonInactive.png);\n"
                                             "border: 0px;")
        self.playerTwoLogin.setStyleSheet("image: url(:/images/logInInactive.png);\n"
                                          "border: 0px;")
        self.playerTwoRegister.setStyleSheet("image: url(:/images/registerButtonInactive.png);\n"
                                             "border: 0px;")
        self.playerThreeLogin.setStyleSheet("image: url(:/images/logInInactive.png);\n"
                                            "border: 0px;")
        self.playerThreeRegister.setStyleSheet("image: url(:/images/registerButtonInactive.png);\n"
                                               "border: 0px;")
        self.playerFourLogin.setStyleSheet("image: url(:/images/logInInactive.png);\n"
                                           "border: 0px;")
        self.playerFourRegister.setStyleSheet("image: url(:/images/registerButtonInactive.png);\n"
                                              "border: 0px;")

    def onePlayer(self):
        self.playerOneLogin.clicked.connect(self.show_login)
        self.playerOneRegister.clicked.connect(self.show_register)

        self.playerTwoLabel.setStyleSheet("image: url(:/images/playerTwoInactive.png);")
        self.playerThreeLabel.setStyleSheet("image: url(:/images/playerThreeInactive.png);")
        self.playerFourLabel.setStyleSheet("image: url(:/images/playerFourInactive.png);")

        self.playerTwoLogin.setStyleSheet("image: url(:/images/logInInactive.png);\n"
                                          "border: 0px;")
        self.playerTwoRegister.setStyleSheet("image: url(:/images/registerButtonInactive.png);\n"
                                             "border: 0px;")
        self.playerThreeLogin.setStyleSheet("image: url(:/images/logInInactive.png);\n"
                                            "border: 0px;")
        self.playerThreeRegister.setStyleSheet("image: url(:/images/registerButtonInactive.png);\n"
                                               "border: 0px;")
        self.playerFourLogin.setStyleSheet("image: url(:/images/logInInactive.png);\n"
                                           "border: 0px;")
        self.playerFourRegister.setStyleSheet("image: url(:/images/registerButtonInactive.png);\n"
                                              "border: 0px;")

    def twoPlayers(self):
        self.playerOneLogin.clicked.connect(self.show_login)
        self.playerOneRegister.clicked.connect(self.show_register)
        self.playerTwoLogin.clicked.connect(self.show_login)
        self.playerTwoRegister.clicked.connect(self.show_register)

        self.playerThreeLabel.setStyleSheet("image: url(:/images/playerThreeInactive.png);")
        self.playerFourLabel.setStyleSheet("image: url(:/images/playerFourInactive.png);")

        self.playerThreeLogin.setStyleSheet("image: url(:/images/logInInactive.png);\n"
                                            "border: 0px;")
        self.playerThreeRegister.setStyleSheet("image: url(:/images/registerButtonInactive.png);\n"
                                               "border: 0px;")
        self.playerFourLogin.setStyleSheet("image: url(:/images/logInInactive.png);\n"
                                           "border: 0px;")
        self.playerFourRegister.setStyleSheet("image: url(:/images/registerButtonInactive.png);\n"
                                              "border: 0px;")

    def threePlayers(self):
        self.playerOneLogin.clicked.connect(self.show_login)
        self.playerOneRegister.clicked.connect(self.show_register)
        self.playerTwoLogin.clicked.connect(self.show_login)
        self.playerTwoRegister.clicked.connect(self.show_register)
        self.playerThreeLogin.clicked.connect(self.show_login)
        self.playerThreeRegister.clicked.connect(self.show_register)

        self.playerFourLabel.setStyleSheet("image: url(:/images/playerFourInactive.png);")

        self.playerFourLogin.setStyleSheet("image: url(:/images/logInInactive.png);\n"
                                           "border: 0px;")
        self.playerFourRegister.setStyleSheet("image: url(:/images/registerButtonInactive.png);\n"
                                              "border: 0px;")

    def fourPlayers(self):
        self.playerOneLogin.clicked.connect(self.show_login)
        self.playerOneRegister.clicked.connect(self.show_register)
        self.playerTwoLogin.clicked.connect(self.show_login)
        self.playerTwoRegister.clicked.connect(self.show_register)
        self.playerThreeLogin.clicked.connect(self.show_login)
        self.playerThreeRegister.clicked.connect(self.show_register)
        self.playerFourLogin.clicked.connect(self.show_login)
        self.playerFourRegister.clicked.connect(self.show_register)

    def zeroComputers(self):
        self.compOneLabel.setStyleSheet("image: url(:/images/computerOneInactive.png);")
        self.compTwoLabel.setStyleSheet("image: url(:/images/computerTwoInactive.png);")
        self.compThreeLabel.setStyleSheet("image: url(:/images/computerThreeInactive.png);")
        self.compFourLabel.setStyleSheet("image: url(:/images/computerFourInactive.png);")
        self.compOneEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                             "border: 0px;")
        self.compTwoEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                             "border: 0px;")
        self.compThreeEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                               "border: 0px;")
        self.compFourEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                              "border: 0px;")
        self.compOneMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                               "border: 0px;")
        self.compTwoMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                               "border: 0px;")
        self.compThreeMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                                 "border: 0px;")
        self.compFourMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                                "border: 0px;")
        self.compOneHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                             "border: 0px;")
        self.compTwoHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                             "border: 0px;")
        self.compThreeHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                               "border: 0px;")
        self.compFourHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                              "border: 0px;")

    def oneComputer(self):
        self.compOneEasyButton.clicked.connect(self.compOneEasyLevel)
        self.compOneMediumButton.clicked.connect(self.compOneMediumLevel)
        self.compOneHardButton.clicked.connect(self.compOneHardLevel)

        self.compOneLabel.setStyleSheet("image: url(:/images/computerOne.png);")
        self.compTwoLabel.setStyleSheet("image: url(:/images/computerTwoInactive.png);")
        self.compThreeLabel.setStyleSheet("image: url(:/images/computerThreeInactive.png);")
        self.compFourLabel.setStyleSheet("image: url(:/images/computerFourInactive.png);")

        self.compOneEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                             "border: 0px;")
        self.compTwoEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                             "border: 0px;")
        self.compThreeEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                               "border: 0px;")
        self.compFourEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                              "border: 0px;")
        self.compOneMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                               "border: 0px;")
        self.compTwoMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                               "border: 0px;")
        self.compThreeMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                                 "border: 0px;")
        self.compFourMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                                "border: 0px;")
        self.compOneHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                             "border: 0px;")
        self.compTwoHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                             "border: 0px;")
        self.compThreeHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                               "border: 0px;")
        self.compFourHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                              "border: 0px;")

    def twoComputers(self):
        self.compOneEasyButton.clicked.connect(self.compOneEasyLevel)
        self.compOneMediumButton.clicked.connect(self.compOneMediumLevel)
        self.compOneHardButton.clicked.connect(self.compOneHardLevel)
        self.compTwoEasyButton.clicked.connect(self.compTwoEasyLevel)
        self.compTwoMediumButton.clicked.connect(self.compTwoMediumLevel)
        self.compTwoHardButton.clicked.connect(self.compTwoHardLevel)

        self.compOneLabel.setStyleSheet("image: url(:/images/computerOne.png);")
        self.compTwoLabel.setStyleSheet("image: url(:/images/computerTwo.png);")
        self.compThreeLabel.setStyleSheet("image: url(:/images/computerThreeInactive.png);")
        self.compFourLabel.setStyleSheet("image: url(:/images/computerFourInactive.png);")

        self.compOneEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                             "border: 0px;")
        self.compTwoEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                             "border: 0px;")
        self.compThreeEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                               "border: 0px;")
        self.compFourEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                              "border: 0px;")
        self.compOneMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                               "border: 0px;")
        self.compTwoMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                               "border: 0px;")
        self.compThreeMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                                 "border: 0px;")
        self.compFourMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                                "border: 0px;")
        self.compOneHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                             "border: 0px;")
        self.compTwoHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                             "border: 0px;")
        self.compThreeHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                               "border: 0px;")
        self.compFourHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                              "border: 0px;")

    def threeComputers(self):
        self.compOneEasyButton.clicked.connect(self.compOneEasyLevel)
        self.compOneMediumButton.clicked.connect(self.compOneMediumLevel)
        self.compOneHardButton.clicked.connect(self.compOneHardLevel)
        self.compTwoEasyButton.clicked.connect(self.compTwoEasyLevel)
        self.compTwoMediumButton.clicked.connect(self.compTwoMediumLevel)
        self.compTwoHardButton.clicked.connect(self.compTwoHardLevel)
        self.compThreeEasyButton.clicked.connect(self.compThreeEasyLevel)
        self.compThreeMediumButton.clicked.connect(self.compThreeMediumLevel)
        self.compThreeHardButton.clicked.connect(self.compThreeHardLevel)

        self.compOneLabel.setStyleSheet("image: url(:/images/computerOne.png);")
        self.compTwoLabel.setStyleSheet("image: url(:/images/computerTwo.png);")
        self.compThreeLabel.setStyleSheet("image: url(:/images/computerThree.png);")
        self.compFourLabel.setStyleSheet("image: url(:/images/computerFourInactive.png);")

        self.compOneEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                             "border: 0px;")
        self.compTwoEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                             "border: 0px;")
        self.compThreeEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                               "border: 0px;")
        self.compFourEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                              "border: 0px;")
        self.compOneMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                               "border: 0px;")
        self.compTwoMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                               "border: 0px;")
        self.compThreeMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                                 "border: 0px;")
        self.compFourMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                                "border: 0px;")
        self.compOneHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                             "border: 0px;")
        self.compTwoHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                             "border: 0px;")
        self.compThreeHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                               "border: 0px;")
        self.compFourHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                              "border: 0px;")

    def fourComputers(self):
        self.compOneEasyButton.clicked.connect(self.compOneEasyLevel)
        self.compOneMediumButton.clicked.connect(self.compOneMediumLevel)
        self.compOneHardButton.clicked.connect(self.compOneHardLevel)
        self.compTwoEasyButton.clicked.connect(self.compTwoEasyLevel)
        self.compTwoMediumButton.clicked.connect(self.compTwoMediumLevel)
        self.compTwoHardButton.clicked.connect(self.compTwoHardLevel)
        self.compThreeEasyButton.clicked.connect(self.compThreeEasyLevel)
        self.compThreeMediumButton.clicked.connect(self.compThreeMediumLevel)
        self.compThreeHardButton.clicked.connect(self.compThreeHardLevel)
        self.compFourEasyButton.clicked.connect(self.compFourEasyLevel)
        self.compFourMediumButton.clicked.connect(self.compFourMediumLevel)
        self.compFourHardButton.clicked.connect(self.compFourHardLevel)

    # Wygaszanie nieużywanych opcji + przypisywanie poziomów do zmiennych

    # Poziomy pierwszego komputera

    def compOneEasyLevel(self):
        self.computerOneLevel = 1
        self.compOneEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                             "border: 0px;")
        self.compOneMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                               "border: 0px;")
        self.compOneHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                             "border: 0px;")

    def compOneMediumLevel(self):
        self.computerOneLevel = 2
        self.compOneEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                             "border: 0px;")
        self.compOneMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                               "border: 0px;")
        self.compOneHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                             "border: 0px;")

    def compOneHardLevel(self):
        self.computerOneLevel = 3
        self.compOneEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                             "border: 0px;")
        self.compOneMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                               "border: 0px;")
        self.compOneHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                             "border: 0px;")

        # Poziomy drugiego komputera

    def compTwoEasyLevel(self):
        self.computerTwoLevel = 1
        self.compTwoEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                             "border: 0px;")
        self.compTwoMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                               "border: 0px;")
        self.compTwoHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                             "border: 0px;")

    def compTwoMediumLevel(self):
        self.computerTwoLevel = 2
        self.compTwoEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                             "border: 0px;")
        self.compTwoMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                               "border: 0px;")
        self.compTwoHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                             "border: 0px;")

    def compTwoHardLevel(self):
        self.computerTwoLevel = 3
        self.compTwoEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                             "border: 0px;")
        self.compTwoMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                               "border: 0px;")
        self.compTwoHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                             "border: 0px;")

        # Poziomy trzeciego komputera

    def compThreeEasyLevel(self):
        self.computerThreeLevel = 1
        self.compThreeEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                               "border: 0px;")
        self.compThreeMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                                 "border: 0px;")
        self.compThreeHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                               "border: 0px;")

    def compThreeMediumLevel(self):
        self.computerThreeLevel = 2
        self.compThreeEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                               "border: 0px;")
        self.compThreeMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                                 "border: 0px;")
        self.compThreeHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                               "border: 0px;")

    def compThreeHardLevel(self):
        self.computerThreeLevel = 3
        self.compThreeEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                               "border: 0px;")
        self.compThreeMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                                 "border: 0px;")
        self.compThreeHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                               "border: 0px;")

        # Poziomy czwartego komputera

    def compFourEasyLevel(self):
        self.computerFourLevel = 1
        self.compFourEasyButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                              "border: 0px;")
        self.compFourMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                                "border: 0px;")
        self.compFourHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                              "border: 0px;")

    def compFourMediumLevel(self):
        self.computerFourLevel = 2
        self.compFourEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                              "border: 0px;")
        self.compFourMediumButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                                "border: 0px;")
        self.compFourHardButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                              "border: 0px;")

    def compFourHardLevel(self):
        self.computerFourLevel = 3
        self.compFourEasyButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                              "border: 0px;")
        self.compFourMediumButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                                "border: 0px;")
        self.compFourHardButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                              "border: 0px;")

        # Wygaszanie poziomu gry

    def easyLevel(self):
        self.gameLevel = 1
        self.easyGameButton.setStyleSheet("image: url(:/images/easy.png);\n"
                                          "border: 0px;")
        self.easyLabel.setStyleSheet("image: url(:/images/easyTiming.png);")
        self.mediumLabel.setStyleSheet("image: url(:/images/mediumTimingInactive.png);")
        self.mediumGameButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                            "border: 0px;")
        self.hardLabel.setStyleSheet("image: url(:/images/hardTimingInactive.png);")
        self.hardGameButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                          "border: 0px;")

    def mediumLevel(self):
        self.gameLevel = 2
        self.mediumGameButton.setStyleSheet("image: url(:/images/medium.png);\n"
                                            "border: 0px;")
        self.mediumLabel.setStyleSheet("image: url(:/images/mediumTiming.png);")
        self.easyLabel.setStyleSheet("image: url(:/images/easyTimingInactive.png);")
        self.easyGameButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                          "border: 0px;")
        self.hardLabel.setStyleSheet("image: url(:/images/hardTimingInactive.png);")
        self.hardGameButton.setStyleSheet("image: url(:/images/hardInactive.png);\n"
                                          "border: 0px;")

    def hardLevel(self):
        self.gameLevel = 3
        self.hardLabel.setStyleSheet("image: url(:/images/hardTiming.png);")
        self.hardGameButton.setStyleSheet("image: url(:/images/hard.png);\n"
                                          "border: 0px;")
        self.easyLabel.setStyleSheet("image: url(:/images/easyTimingInactive.png);")
        self.easyGameButton.setStyleSheet("image: url(:/images/easyInactive.png);\n"
                                          "border: 0px;")

        self.mediumLabel.setStyleSheet("image: url(:/images/mediumTimingInactive.png);")
        self.mediumGameButton.setStyleSheet("image: url(:/images/mediumInactive.png);\n"
                                            "border: 0px;")

    def first_player(self):
        self.numberOfPlayer = 1
        self.update_id(self.numberOfPlayer)

    def second_player(self):
        self.numberOfPlayer = 2
        self.update_id(self.numberOfPlayer)

    def third_player(self):
        self.numberOfPlayer = 3
        self.update_id(self.numberOfPlayer)

    def fourth_player(self):
        self.numberOfPlayer = 4
        self.update_id(self.numberOfPlayer)

    def update_id(self, user_id):
        try:
            db = sql.connect('siema.db')  # łączymy się do bazy
            c = db.cursor()  # dodajemy kursor

            c.execute("UPDATE logged_users SET id = {} WHERE id = 0".format(user_id))
            db.commit()


        except sql.Error as e:
            print("Error")


    def show_register(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = registerEng.registerEngForm()
        self.ui.setupUi(self.window)
        self.window.show()

    def show_login(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = loginEng.loginForm()
        self.ui.setupUi(self.window)
        self.window.show()


