# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class warningDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(399, 301)
        self.background = QtWidgets.QLabel(Dialog)
        self.background.setGeometry(QtCore.QRect(9, 10, 381, 281))
        self.background.setStyleSheet("background-color: rgb(24, 47, 38);")
        self.background.setText("")
        self.background.setObjectName("background")
        self.warningIcon = QtWidgets.QLabel(Dialog)
        self.warningIcon.setGeometry(QtCore.QRect(154, 50, 91, 81))
        self.warningIcon.setStyleSheet("image: url(:/images/warning.png);")
        self.warningIcon.setText("")
        self.warningIcon.setObjectName("warningIcon")
        self.warningText = QtWidgets.QLabel(Dialog)
        self.warningText.setGeometry(QtCore.QRect(50, 140, 301, 121))
        self.warningText.setStyleSheet("image: url(:/images/warningText.png);")
        self.warningText.setText("")
        self.warningText.setObjectName("warningText")
        self.orangeBackground = QtWidgets.QLabel(Dialog)
        self.orangeBackground.setGeometry(QtCore.QRect(-1, 0, 401, 301))
        self.orangeBackground.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.orangeBackground.setText("")
        self.orangeBackground.setObjectName("orangeBackground")
        self.orangeBackground.raise_()
        self.background.raise_()
        self.warningIcon.raise_()
        self.warningText.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Error", "Error"))

